### ISSUE TITLE
Changing the github username is not recognized

### ISSUE THREAD

**Issue by patrick-hofmann** [nuxt/nuxters#115]
It seems that changing the github username is not reflected correctly on the nuxters page. I get my old github username returned - even in incognito browser windows, so it doesn't seem to be a caching issue.

**Comment by ayanoakune** [comment]
Yes, it's because Nuxt stores the contributors data - both your Github username and Github id (user id). So when you change your username, Nuxt doesn't see that change and finds you in the contributors list via Github id. 

Data is available here: https://api.nuxt.com/contributors

My suggestion for fix: When user logins into `nuxters.nuxt.com`, send request to "https://api.github.com/user/<github_id>" and see if data matches, if not update the name. I don't know where or how the code behind it all works, but something like that maybe could work.

Thinking a little more - Nuxt API and Nuxters are probably two separate things, so I'm doubting that it's that easy.

Also, I had same problem - and I fixed it myself. I had made 2 comments under my old username. I deleted both of them (they were not that important/impactful). This made Nuxt API to remove me from contributors list. Then under my current name I commented/helped on new Nuxt issue and got added back as with my current username. I don't recommend this approach, only if you have 1-2 comments like I did.

**Comment by arashsheyda** [comment]
yes the contributors data is stored and cached. that's the reason if you give it some time the cache would get updated (as I checked now it's updated) I don't think there's much that we can do (or needed)

**Comment by ayanoakune** [comment]
How long is it cached for? My old name was shown for several months, maybe even a year. 🤔 

It would be nice if user could delete their data. This would also solve compliance with GDPR (I guess?). 😄 

I also feel it's okay to not change anything at the moment. Maybe shorten cache period if it's too long (if cache was the real problem for Patrick).

**Comment by patrick-hofmann** [comment]
So although https://api.nuxt.com/contributers shows the new GitHub name, the page https://nuxters.nuxt.com still shows the old user name after login

![image](https://github.com/user-attachments/assets/cb71f98f-0be8-41c0-bc08-7a465d857112)

**Comment by patrick-hofmann** [comment]
delta-mind-phofmann -> patrick-hofmann

Thx @atinux

**Comment by atinux** [comment]
It's good: https://nuxters.nuxt.com/patrick-hofmann
